[workspace]
members = ["crates/*"]

[package]
name = "wyag"
version = "0.1.0"
edition = "2021"

[dependencies]
application = { path = "crates/application" }
configparser = "3.1.0"
thiserror = "1.0.64"
